# Generated by Django 4.2.2 on 2023-07-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_creation_date',
            field=models.DateField(auto_now=True),
        ),
    ]
