# Generated by Django 4.2.2 on 2023-07-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capital', '0002_alter_wallet_wallet_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
