# Generated by Django 4.2.2 on 2023-07-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capital', '0003_wallet_wallet_edited_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_edited_date',
            field=models.DateField(auto_now=True),
        ),
    ]
