# Generated by Django 4.2.2 on 2023-07-30 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Capital', '0004_alter_wallet_wallet_edited_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_type', models.CharField(choices=[('Housing', 'Housing'), ('Utilities', 'Utilities'), ('Transportation', 'Transportation'), ('Food and Beverages', 'Food and Beverages'), ('Health', 'Health'), ('Entertainment', 'Entertainment'), ('Debt Payment', 'Debt Payment'), ('Education', 'Education'), ('Miscellaneous', 'Miscellaneous')], max_length=50)),
                ('expense_date', models.DateField(auto_now_add=True)),
                ('parent_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Capital.wallet')),
            ],
        ),
    ]
